PREFIX=/usr

all:
	@echo "This software is interpreted, no compilation needed"
install:
	cp jumpnbump_menu.glade $(PREFIX)/share/games/jumpnbump/
	cp jumpnbump_menu.py $(PREFIX)/games/

uninstall:
	rm $(PREFIX)/share/games/jumpnbump/jumpnbump_menu.glade
	rm $(PREFIX)/games/jumpnbump_menu.py
